package com.resumeradar.service;

import com.resumeradar.entity.MatchedKeyword;
import com.resumeradar.entity.MissingKeyword;
import com.resumeradar.entity.ResumeAnalysis;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class PdfReportService {

	private static final Logger LOGGER = LoggerFactory.getLogger(PdfReportService.class);

	private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a");

	private static final float MARGIN = 54;

	private static final float LINE_HEIGHT = 15;

	private static final float SECTION_GAP = 12;

	private static final String FOOTER_TEXT = "Generated by ResumeRadar ATS Engine";

	private final PDFont regularFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

	private final PDFont boldFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

	public byte[] generateReport(ResumeAnalysis analysis) {
		try (PDDocument document = new PDDocument();
			 ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
			PdfWriter writer = new PdfWriter(document);

			writer.writeHeader();
			writer.writeSectionTitle("Candidate");
			writer.writeKeyValue("User Name", analysis.getUser() == null ? null : analysis.getUser().getFullName());
			writer.writeKeyValue("Email", analysis.getUser() == null ? null : analysis.getUser().getEmail());
			writer.writeKeyValue("Analysis Date", formatDate(analysis.getCreatedAt()));

			writer.writeSectionTitle("Analysis");
			writer.writeKeyValue("Resume File Name", analysis.getResumeFileName());
			writer.writeKeyValue("ATS Score", analysis.getAtsScore() == null ? "N/A" : analysis.getAtsScore() + "%");
			writer.writeKeyValue("Overall Feedback", analysis.getOverallFeedback());

			writer.writeSectionTitle("Matched Keywords");
			writer.writeBullets(toMatchedKeywords(analysis));

			writer.writeSectionTitle("Missing Keywords");
			writer.writeBullets(toMissingKeywords(analysis));

			writer.writeSectionTitle("AI Suggestions");
			writer.writeParagraph(nonBlank(analysis.getAiSuggestions(), AiSuggestionService.FALLBACK_MESSAGE));

			writer.writeFooter();
			writer.close();

			document.save(outputStream);
			return outputStream.toByteArray();
		} catch (Exception exception) {
			LOGGER.error(
				"Failed to generate PDF report for analysisId={}: {}",
				analysis == null ? null : analysis.getId(),
				exception.getMessage(),
				exception
			);
			throw new IllegalStateException("Failed to generate PDF report", exception);
		}
	}

	private List<String> toMatchedKeywords(ResumeAnalysis analysis) {
		if (analysis.getMatchedKeywords() == null) {
			return List.of();
		}

		return analysis.getMatchedKeywords()
			.stream()
			.map(MatchedKeyword::getKeyword)
			.toList();
	}

	private List<String> toMissingKeywords(ResumeAnalysis analysis) {
		if (analysis.getMissingKeywords() == null) {
			return List.of();
		}

		return analysis.getMissingKeywords()
			.stream()
			.map(MissingKeyword::getKeyword)
			.toList();
	}

	private String formatDate(LocalDateTime dateTime) {
		return dateTime == null ? "N/A" : dateTime.format(DATE_FORMATTER);
	}

	private String nonBlank(String value, String fallback) {
		return value == null || value.isBlank() ? fallback : value;
	}

	private class PdfWriter {

		private final PDDocument document;

		private PDPage page;

		private PDPageContentStream contentStream;

		private float y;

		PdfWriter(PDDocument document) throws IOException {
			this.document = document;
			addPage();
		}

		void writeHeader() throws IOException {
			contentStream.setNonStrokingColor(37, 99, 235);
			contentStream.addRect(0, page.getMediaBox().getHeight() - 92, page.getMediaBox().getWidth(), 92);
			contentStream.fill();
			contentStream.setNonStrokingColor(255, 255, 255);
			writeLine("ResumeRadar", boldFont, 20, MARGIN, page.getMediaBox().getHeight() - 40);
			writeLine("ATS Resume Analysis Report", boldFont, 15, MARGIN, page.getMediaBox().getHeight() - 66);
			contentStream.setNonStrokingColor(17, 24, 39);
			y = page.getMediaBox().getHeight() - 120;
		}

		void writeSectionTitle(String title) throws IOException {
			ensureSpace(42);
			y -= SECTION_GAP;
			contentStream.setNonStrokingColor(37, 99, 235);
			writeLine(title, boldFont, 13.5f, MARGIN, y);
			contentStream.setNonStrokingColor(229, 231, 235);
			contentStream.moveTo(MARGIN, y - 7);
			contentStream.lineTo(page.getMediaBox().getWidth() - MARGIN, y - 7);
			contentStream.stroke();
			contentStream.setNonStrokingColor(17, 24, 39);
			y -= 24;
		}

		void writeKeyValue(String label, String value) throws IOException {
			ensureSpace(40);
			writeLine(label + ":", boldFont, 10.5f, MARGIN, y);
			y -= LINE_HEIGHT;
			writeWrapped(nonBlank(value, "N/A"), regularFont, 10.5f, MARGIN + 14, getContentWidth() - 14);
			y -= 3;
		}

		void writeBullets(List<String> values) throws IOException {
			if (values == null || values.isEmpty()) {
				writeParagraph("No keywords found.");
				return;
			}

			for (String value : values) {
				writeWrapped("- " + nonBlank(value, "N/A"), regularFont, 10.5f, MARGIN, getContentWidth());
			}
		}

		void writeParagraph(String text) throws IOException {
			writeWrapped(text, regularFont, 10.5f, MARGIN, getContentWidth());
		}

		void writeFooter() throws IOException {
			ensureSpace(40);
			y -= 12;
			contentStream.setNonStrokingColor(107, 114, 128);
			writeWrapped(
				FOOTER_TEXT + " | Report Generation Timestamp: " + LocalDateTime.now().format(DATE_FORMATTER),
				regularFont,
				8.5f,
				MARGIN,
				getContentWidth()
			);
			contentStream.setNonStrokingColor(17, 24, 39);
		}

		void close() throws IOException {
			if (contentStream != null) {
				contentStream.close();
			}
		}

		private void writeWrapped(String text, PDFont font, float fontSize, float x, float maxWidth) throws IOException {
			String normalizedText = sanitize(nonBlank(text, "N/A")).replace("\r", "");
			for (String paragraph : normalizedText.split("\n", -1)) {
				List<String> lines = wrapText(paragraph, font, fontSize, maxWidth);
				if (lines.isEmpty()) {
					y -= LINE_HEIGHT;
					continue;
				}

				for (String line : lines) {
					ensureSpace(LINE_HEIGHT + 4);
					writeLine(line, font, fontSize, x, y);
					y -= LINE_HEIGHT;
				}
				y -= 3;
			}
		}

		private List<String> wrapText(String text, PDFont font, float fontSize, float maxWidth) throws IOException {
			List<String> lines = new ArrayList<>();
			String normalizedText = sanitize(text);
			if (normalizedText.isBlank()) {
				return lines;
			}

			StringBuilder line = new StringBuilder();
			for (String word : normalizedText.split("\\s+")) {
				for (String piece : splitLongWord(word, font, fontSize, maxWidth)) {
					String candidate = line.isEmpty() ? piece : line + " " + piece;
					if (textWidth(candidate, font, fontSize) <= maxWidth) {
						line = new StringBuilder(candidate);
					} else {
						if (!line.isEmpty()) {
							lines.add(line.toString());
						}
						line = new StringBuilder(piece);
					}
				}
			}

			if (!line.isEmpty()) {
				lines.add(line.toString());
			}

			return lines;
		}

		private List<String> splitLongWord(String word, PDFont font, float fontSize, float maxWidth) throws IOException {
			if (textWidth(word, font, fontSize) <= maxWidth) {
				return List.of(word);
			}

			List<String> pieces = new ArrayList<>();
			StringBuilder piece = new StringBuilder();
			for (char character : word.toCharArray()) {
				String candidate = piece.toString() + character;
				if (textWidth(candidate, font, fontSize) <= maxWidth) {
					piece.append(character);
				} else {
					if (!piece.isEmpty()) {
						pieces.add(piece.toString());
					}
					piece = new StringBuilder(String.valueOf(character));
				}
			}

			if (!piece.isEmpty()) {
				pieces.add(piece.toString());
			}

			return pieces;
		}

		private float textWidth(String text, PDFont font, float fontSize) throws IOException {
			return font.getStringWidth(sanitize(text)) / 1000 * fontSize;
		}

		private void ensureSpace(float requiredSpace) throws IOException {
			if (y - requiredSpace < MARGIN) {
				addPage();
			}
		}

		private void addPage() throws IOException {
			if (contentStream != null) {
				contentStream.close();
			}

			page = new PDPage(PDRectangle.LETTER);
			document.addPage(page);
			contentStream = new PDPageContentStream(document, page);
			contentStream.setNonStrokingColor(17, 24, 39);
			y = page.getMediaBox().getHeight() - MARGIN;
		}

		private void writeLine(String text, PDFont font, float fontSize, float x, float textY) throws IOException {
			String safeText = sanitize(text);
			if (safeText.isBlank()) {
				return;
			}

			contentStream.beginText();
			contentStream.setFont(font, fontSize);
			contentStream.newLineAtOffset(x, textY);
			contentStream.showText(safeText);
			contentStream.endText();
		}

		private float getContentWidth() {
			return page.getMediaBox().getWidth() - (MARGIN * 2);
		}

		private String sanitize(String text) {
			return nonBlank(text, "N/A")
				.replace("\t", " ")
				.replace("\u00a0", " ")
				.replaceAll("[\\p{Cntrl}&&[^\r\n]]", " ")
				.replaceAll("[^\\x20-\\x7E\\r\\n]", "");
		}
	}
}
